### ISSUE TITLE
Failed to run custom build command

### ISSUE THREAD

**Issue by triccs** [osmosis-labs/test-tube#10]
![image](https://user-images.githubusercontent.com/105668529/216643097-9da3073b-0771-49a0-a8a6-da19036af9f4.png)

I've cleaned and reset the registry, still can't build

**Comment by iboss-ptk** [comment]
Which OS are you on?

**Comment by triccs** [comment]
Windows 11 using WSL 2

I apologize for opening and closing so much, I thought I had a solution. The build works for the initial 0.1.0 version but none of the others.
