### ISSUE TITLE
Conflicting `osmosis-std` versions causing build failure.

### ISSUE THREAD

**Issue by CyberHoward** [osmosis-labs/test-tube#38]
The current version of test-tube and osmosis-test-tube have conflicting versions for `osmosis-std`, causing our builds to fail as shown [here](https://github.com/AbstractSDK/cw-orchestrator/actions/runs/5880673820/job/15947475354). 

This problem is persistent for most versions we tried. 

Can `osmosis-std` be omitted from `test-tube` itself?

```bash
> cargo tree -i osmosis-std@0.16.2
osmosis-std v0.16.2
└── osmosis-test-tube v16.1.2
    └── cw-orch v0.13.3 (/Users/robin/Programming/Abstract/cw-orch/cw-orch)
        
> cargo tree -i osmosis-std@0.17.0-rc0
osmosis-std v0.17.0-rc0
└── test-tube v0.1.6
    └── osmosis-test-tube v16.1.2
        └── cw-orch v0.13.3 (/Users/robin/Programming/Abstract/cw-orch/cw-orch)
```

**Comment by apollo-sturdy** [comment]
I brought this up to @iboss-ptk in DMs the other day. The version bump of osmosis-std in test-tube should have resulted in a new major version of test-tube. In the mean time you can solve it by specifying exact versions like this:
```toml
osmosis-std = "=0.16.1"
test-tube = "=0.1.5"
```
