### ISSUE TITLE
panic: unlinkat /tmp/.osmosis-test-tube-temp-3820962552/data: directory not empty

### ISSUE THREAD

**Issue by Buckram123** [osmosis-labs/test-tube#52]
I'm getting random `panic: unlinkat /tmp/.osmosis-test-tube-temp-3820962552/data: directory not empty` during tests and in CI: https://github.com/AbstractSDK/carrot-app/actions/runs/8879573463/job/24377599948?pr=84#step:8:919
The worst part that it's not consistent, restarting action just fixes it magically

**Comment by Buckram123** [comment]
![image](https://github.com/osmosis-labs/test-tube/assets/91957742/f3f1412b-e147-496f-9a0d-6100c14952ed)

**Comment by iboss-ptk** [comment]
Could be a concurrency problem. Every new app [creates tmp dir](https://github.com/osmosis-labs/test-tube/blob/a7e1de5a8067d369aa4b8f7edc56be41299aedfa/packages/osmosis-test-tube/libosmosistesttube/main.go#L56-L59) using [os.MkdirTemp](https://pkg.go.dev/os#MkdirTemp) and then cleaned up [after the end of it's lifetime](https://github.com/osmosis-labs/test-tube/blob/a7e1de5a8067d369aa4b8f7edc56be41299aedfa/packages/test-tube/src/runner/app.rs#L354-L360) by calling [`CleanUp`](https://github.com/osmosis-labs/test-tube/blob/a7e1de5a8067d369aa4b8f7edc56be41299aedfa/packages/osmosis-test-tube/libosmosistesttube/main.go#L89-L96) which under the hood, calling `os.RemoveAll(nodeHome)` and that's probably what invoke syscall `unlinkat`.

Found a [reference issue](https://github.com/golang/go/issues/23452) noting that other process might try to write to the same dir while it's cleaning up, but theoretically, rust compiler should prevent sharing the app instance and only drop after used unless there are bugs or you use some unsafe magic. 

Mind sharing the code that fails?

**Comment by Buckram123** [comment]
Didn't happen again
